### ISSUE TITLE
There are no portable (split) distributions of stackexchange ZIMs

### ISSUE THREAD

**Issue by Jaifroid** [openzim/overview#2]
Not sure if this is the right place to note this issue. It may be "by design", which is fine, but at least one of the ZIMs for Stackexchange -- stackoverflow.com_eng_all_2017-05.zim -- is 52GB, so a split version could be useful if time/resources permit. Or if not, perhaps a README should be put in the /portable/stackexchange directory pointing people to the FAQ where it explains how to split files manually.

**Comment by kelson42** [comment]
@Jaifroid I have started to slowly do not provide portable versions anymore. The reason is that we have now the embedded index which makes an external index useless. On the top of that, we have made a few changes in the ZIM format recently which bring a few problem with the old code to generate the external index. So, we hope to provide soon the first version of Kiwix-desktop 2.0 to allow users to fully enjoy the new ZIM files with embedded indexes. I will update the docs and wiki pages as soon as Kiwix-destkop 2.0 is put online.

**Comment by Jaifroid** [comment]
@kelson42, this issue was more about splitting very large files (.zimaa, .zimab, etc.) rather than about indexing. If you expect users to split the files themselves, then I would recommend putting a README in the portable folder for Stackexchange (or other empty folders) with an indication of what you say above and how people can split their own files.

**Comment by kelson42** [comment]
@Jaifroid Why do we need a version with chunks? To support FAT32?

**Comment by Jaifroid** [comment]
I think FAT32 is the traditional reason, as explained in http://wiki.kiwix.org/wiki/FAQ/en . NB I'm not saying we need it any more if FAT32 has been superseded for thumb drives, etc. I don't really know what the common format is now -- exFAT?

**Comment by kelson42** [comment]
Yes, exFAT is the future.
