### ISSUE TITLE
wikipedia_tr_all_novid_2019-04.zim  is not browsable

### ISSUE THREAD

**Issue by trappedinspacetime** [openzim/overview#3]
Hi, 
First of all thank you for developing and providing this tool.
I use `Zimserver` python module to serve `zim` archive in `localhost`.
I noticed that `wikipedia_tr_all_novid_2019-04.zim ` wouldn't render the pages, I just see blurry empty pages. I also tried other tools such as [web-archives](https://github.com/birros/web-archives) and [kiwix](https://github.com/kiwix/kiwix-desktop) but none of them worked.

How can I create `zim` archive of `https://tr.wikipedia.org` by myself?
I also  want to inform maintainers of https://download.kiwix.org/zim about the issue.

**Comment by kelson42** [comment]
@trappedinspacetime Thank you for your report. It is not clear what is exactly the problem ia as you use a software which is not ours to read the ZIM file: `Zimserver` and I don't know exactly which page you try to open. I think you should report the problem there (too).

That said we have just a new ZIM files of Wikipedia in Turkish, maybe the problem was in the ZIM file itself. You can see it live served by `kiwix-serve` here http://library.kiwix.org/wikipedia_tr_all_novid_2019-06/. I don't see the problem you report (anymore?). You can download the file from https://download.kiwix.org/zim/wikipedia/.

We don't advise people to create there own ZIM files of Wikipedia. That is why we distribute ZIM files too. These ZIM files are created with a tool called `MWoffliner` https://github.com/openzim/mwoffliner.

Please reopen the ticket if you still have the same problem. If you have any other problem, a new ticket would be welcome.

**Comment by trappedinspacetime** [comment]
@kelson42 Thank you for the update, it's fixed now.
